# nginx proxy address - http://172.17.0.1:3000

name: dokploy
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: dokploy/dokploy:latest
    container_name: dokploy-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    ports:
      - '172.17.0.1:3000:3000'
    volumes:
      - './volumes/data/dokploy:/data'
    networks:
      - dokploy

networks:
  dokploy:
    name: dokploy
    external: false
